# Generated by Django 2.1.7 on 2019-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barrel_No', models.CharField(max_length=10000)),
                ('Barrel_type', models.CharField(max_length=10000)),
                ('Trial_Name', models.CharField(max_length=10000)),
                ('Plot_No', models.CharField(max_length=10000)),
            ],
        ),
    ]
